title: Frank_c
subtitle: My personal website 
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: About
      url: /about


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: frankreal.png
author: Francesco Cirulli
author_bio: Hi, I'm an energetic and ambitious person with a great passion for technological innovation. I firmly believe that good people management is the key to the business success.
            I'm a web3 builder since 2018. In my free time I listen to music, walk and watch movies. I'm a former competitive swimmer.
author_email: "francesco.cirulli96@hotmail.it"
typewrite-text: I'm a web3 builder and Technical Project Manager
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Urbe.eth
              company_logo: urberosso.png
              company_url: https://twitter.com/urbeEth
              designation: community co-founder
              description: Urbe.eth is an italian web3 tech-focused community
              duration: 2022 - now
              visibility: true
            - company_name: Ethereans Lab
              company_logo: logo_main_v.png
              company_url: https://www.ethereanslabs.com/
              designation: Technical Project Manager
              description: Worked on various EthereansOS Products regarding DeFi, on-chain Governance and NFTs
              duration: 2020 - 2022
              visibility: true
            - company_name: Cidaro srl
              company_logo: cidaro.png
              designation: co-founder & COO
              description: co-founded startup which focuses on consulting and developing web3 services for companies
              duration: 2018 - 2021
              visibility: true

# Education
author_education_details:
              - college_logo: luiss.png
                college_name: Luiss Business School (EQUIS accredited)
                college_url: https://businessschool.luiss.it/en/
                college_degree: Project Management
                description: Master's Degree in Project Management
                visibility: true
              - college_logo: torvergata.png
                college_name: University of Rome Tor Vergata
                college_url: https://economia.uniroma2.it/cdl/biennio/clemif
                college_degree: Economics of Financial Markets
                description: Master's Degree in Finance
                visibility: true
              - college_logo: torvergata.png
                college_name: University of Rome Tor Vergata
                college_url: https://economia.uniroma2.it/cdl/triennio/clem
                college_degree: Economics and Management
                description: Bachelor’s Degree Management
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: pogm.png
                project_title: GitGate
                project_description: A DAO framework for GitHub repositories
                project_url: https://web-gitgate.vercel.app/
                documentation: https://seasoned-eocursor-e4d.notion.site/GitGate-7d44be6498344837bf77f1d9e33d308a
                visibility: true
              - project_thumbnail: vKudos.png
                project_title: vKudos
                project_description: vKudos is an ERC721Votes soulbound token allowing a kudos holder to mint its equivalent vKudos to be used in a Governor smart contract and so on the Tally platform
                project_url: https://medium.com/@frankcc/vkudos-a-case-study-for-a-soulbound-721vote-3f8e4995052a
                visibility: true

# social links
twitter_username: Frankc_eth
github_username:  francescocirulli
linkedin_username: francesco-cirulli
medium_username: frankcc
linktree_username: frankcc

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: 

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
